### ISSUE TITLE
Cursor manager keeps track of streams by event name rather than stream id

### ISSUE THREAD

**Issue by whiskeysierra** [zalando-nakadi/fahrschein#222]
See https://github.com/zalando-nakadi/fahrschein/blob/master/fahrschein/src/main/java/org/zalando/fahrschein/ManagedCursorManager.java#L74

That causes issues if the client is shared for multiple connections. Observable behavior includes attempted commits using the wrong stream id.

**Comment by jhorstmann** [comment]
Solving this would probably require refactoring the `CursorManager` interface. It was initially designed for the low level api and reusing it for the subscription api already required workarounds like `addSubscription` and `addStreamId` methods.

Maybe the current `streamId` could be stored inside `NakadiReader` and `CursorManager.onSuccess` could take optional subscription and stream id parameters (maybe wrapped inside a `SubscriptionStream`). But this would introduce a mutable field into `NakadiReader`, which is otherwise immutable, and in theory someone might be trying to reuse the reader from multiple threads.

Until this is solved, there should at least be a note in the readme about needing separate clients when using multiple streams for the same event.

**Comment by horstlaubenthal** [comment]
Another Suggestion for a fix: Maybe you can make the Stream unique to a subscription, not just to its event type name. Subscription takes event-type, application-id and consumer-group into account for being identified.. (and of course you should add a equals to Subscription.class). Then you just need to add possibility to do onSuccess with subscription instead of just event type name. But I think NakadiReader (executing the onSuccess on ManagedCursorManager) already knows something about Subscription..

**Comment by ePaul** [comment]
It took me like 5 minutes finding this issue with a search, so here some key words:

> subscribe to an event type twice
> two subscriptions for same event type
> error 422
