### ISSUE TITLE
Updating the authorization properties of already existing subscriptions

### ISSUE THREAD

**Issue by omarelasfar** [zalando-nakadi/fahrschein#238]
## What needs to be done and why is it needed?

With the roll out of authorization support in fahrschein in this [ticket](https://github.com/zalando-nakadi/fahrschein/issues/234). Users are able to authorize newly created subscription only. This doesn't allow authorization of historical subscriptions created in the past by the library or manually using the Nakadi API. 

As a **software engineer** 
**I want** to be able to authorize all previously created subscription and new ones created by application when using Fahrschein 
**So that** the adaptation of the authorization feature increases and the coverage of authorized events increases  

## What needs to be changed?

1- As soon as an application starts relying on fahrchein with the latest version supporting authorization and the authorization is used by the clients. 
2 - The service fetches all current subscriptions, if some are not authorized the _put_ endpoint is used to update the subscription
3 - Consumption is resumed by the application. 
 
## Acceptance criteria
1 - As a user of the authorization feature on a specific event type this is application while creating the subscription and updated previously existing subscriptions which are authorized. 

## Risks and impact

- Breaking the consuming application if the application itself is not added as a reader and a new deployment blocks the app creating the subscription from consuming a previously working event

**Comment by innokenty** [comment]
This is indeed not a bad idea, it's only not so easy to implement. Code to list subscriptions by event types, getting them, updating them — this is all not implemented currently.

**Comment by whiskeysierra** [comment]
I see several options how to proceed with this:

1. Create subscriptions by hand and specify subscription id when streaming
  - :heavy_check_mark: Easy to implement
  - :heavy_check_mark: No additional call to *find* the subscription
  - :x: Not supported by Fahrschein right now
  - :x: If someone deletes a subscription the application needs to be repaired/redeployed

2. Create subscriptions automatically if absent
  - This is the current mode of operation that Fahrschein supports
  - :heavy_check_mark: Convenient for users since subscriptions are created automatically
  - :x: Not supported by Fahrschein right now
  - :x: Users need to supply admins and readers when streaming which complicates all applications
  - :x: Changing the subscription manually afterwards will result in client code and reality going out of sync

3. Create and update subscription automatically
  - `POST`, compare result, `PUT` if necessary to update
  - :heavy_check_mark: Convenient for users since subscriptions are created automatically
  - :heavy_check_mark: Keeps a single source of truth since the application will enforce a consistent state of the subscription
  - :heavy_check_mark: Applications could only allow themselves as admins, completely locking out any users
  - :x: Manual changes in the UI are either impossible or will be reverted automatically once an hour

**Comment by omarelasfar** [comment]
@whiskeysierra I was proposing option 3 actually. but haven't thought about overriding UI changes with every run. How about POST -> Compare -> Merge -> PUT ?

**Comment by whiskeysierra** [comment]
> How about POST -> Compare -> Merge -> PUT ?

Then you have this problem:

- :x: Changing the subscription manually afterwards will result in client code and reality going out of sync

**Comment by jhorstmann** [comment]
Normally I'd be against adding such logic to a library like fahrschein, since different applications might want different behaviour. The requirements sound very useful though and making subscriptions more secure is a very good goal. So we should at least expose the `PUT` operation and optionally have one or two convenience methods for easier usage. I don't think we should or need to update behaviour of existing methods, since applications will have to be changed anyway to specify the authorization.

This could looke like

```
NakadiClient.updateSubscriptionAuthorization(Subscription subscription, Authorization authorization)
```
To make the common usecase easier we could add

```
SubscriptionBuilder.subscribeAndUpdateAuthorization()
SubscriptionBuilder.subscribeAndInitializeAuthorization()
```

In my opinion, more complex logic like merge belongs into the application.
